spring:
  application:
    name: Moy_LLM_Eto_ne_tvoy_LLM
  main:
    allow-circular-references: true
  ai:
    ollama:
      base-url: http://localhost:11431
      chat:
        model: gemma3:4b-it-q4_K_M
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: postgres
    password: postgres
  # ai:
  #   vectorstore:
  #     pgvector:
  #       table-name:

app:
  knowledgebase:
    path: knowledgebase

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG