spring:
  application:
    name: Moy_LLM
  messages:
    basename: messages
    encoding: UTF-8
  main:
    allow-circular-references: true
  ai:
    ollama:
      chat:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  # ai:
  #   vectorstore:
  #     pgvector:
  #       table-name:

app:
  knowledgebase:
    path: knowledgebase

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG